version: 0.2
env:
  variables:
    PROJECT: MultiSite
    DOTNET_FRAMEWORK: 6.0

phases:
  install:
    runtime-versions:
      dotnet: ${DOTNET_FRAMEWORK}
      nodejs: latest
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore
      - npm install webpack-cli webpack
  build:
    commands:
      - echo Build started on `date`
      - dotnet build -c Release
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 -o ./build_output ./${PROJECT}.csproj --self-contained false
      - cp Procfile ./build_output
artifacts:
  files:
    - "**/*"
  base-directory: ./build_output
  discard-paths: no
