//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Business_locations
{
	/// <summary>
	/// Represents a content item of type <see cref="BusinessLocations"/>.
	/// </summary>
	public partial class BusinessLocations
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "business_locations.BusinessLocations";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// Business_Location_Name.
		/// </summary>
		public string Business_Location_Name { get; set; }


		/// <summary>
		/// Tags.
		/// </summary>
		public string Tags { get; set; }
	}
}