//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.MediaLibrary;

namespace Photosnap
{
	/// <summary>
	/// Represents a content item of type <see cref="CTAContent"/>.
	/// </summary>
	public partial class CTAContent
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Photosnap.CTAContent";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// HeaderText.
		/// </summary>
		public string HeaderText { get; set; }


		/// <summary>
		/// CTAText.
		/// </summary>
		public string CTAText { get; set; }


		/// <summary>
		/// ButtonText.
		/// </summary>
		public string ButtonText { get; set; }


		/// <summary>
		/// Image.
		/// </summary>
		public IEnumerable<AssetRelatedItem> Image { get; set; }
	}
}