//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Test
{
	/// <summary>
	/// Represents a content item of type <see cref="Example"/>.
	/// </summary>
	public partial class Example
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Test.Example";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// Text.
		/// </summary>
		public string Text { get; set; }


		/// <summary>
		/// GUID.
		/// </summary>
		public Guid GUID { get; set; }
	}
}